### ISSUE TITLE
For Delta?

### ISSUE THREAD

**Issue by lolisakio** [michthom/MIDI-to-CNC#6]
Can I use this code  for delta printer?

**Comment by michthom** [comment]
I suspect not, since your Delta printer interprets the Gcode for X/Y/Z moves in its own reverse-kinematic way, you don’t have direct control over the motor stepping rates as with a cartesian machine.

However, it’s perfectly possible to create a similar effect on a delta mechanism, but you’d have to either be able to drive each motor directly, skipping the normal Gcode to delta transformation that the controller board does for you, or else somehow map the movements of the endpoint to a warped geometry that results in “pure” linear motion on each of your delta axes.

That sounds like either a horrible hack (bypassing the controller) or a graduate-level maths project!

If you have the stomach for either, I salute you, but I’d suggest it’s probably not worth the (limited!) joy of hearing your machine’s singing voice? ;-)
